export const AUTH_CLIENT_ID = 'XXXXXX'
export const AUTH_DOMAIN = 'https://dev-XXXXXXXXX.auth0.com'
export const ID_TOKEN_KEY = 'aaa-aaa-token'
export const NONCE_KEY = 'aaa-nonce'
export const GRAPHQL_ENDPOINT = 'http://123.45.121.191/v1/graphql'
export const AUTH_NAMESPACE = 'https://user'
